import os
import json
from .tools.detect import detect_os
from .tools.prereqs import check_prerequisites
from .tools.scan import run_scan
from .tools.parse import parse_results
from .tools.remediate import remediate
from .tools.report import generate_report

SYSTEM_PROMPT = """You are stigman, an AI assistant that runs DISA STIG compliance scans on Ubuntu systems using OpenSCAP. You help users scan their system, understand results, and remediate findings. You have access to tools for OS detection, prerequisite checking, scanning, parsing results, and remediation. Always detect the OS and check prerequisites before scanning. When presenting results, summarize pass/fail counts and highlight critical failures. When asked to remediate, confirm what will be changed before applying fixes. Be concise and terminal-friendly in your responses — no markdown headers or bullet points, use simple text formatting."""

TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "detect_os",
            "description": "Runs lsb_release -a to confirm Ubuntu 24.04.",
            "parameters": {"type": "object", "properties": {}}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "check_prerequisites",
            "description": "Checks if openscap-scanner and ssg-ubuntu2404 are installed, and installs them if missing.",
            "parameters": {"type": "object", "properties": {}}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "run_scan",
            "description": "Runs DISA STIG scan via oscap xccdf eval.",
            "parameters": {"type": "object", "properties": {}}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "parse_results",
            "description": "Parses XCCDF results XML and returns JSON array of rules and their pass/fail status.",
            "parameters": {"type": "object", "properties": {}}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "remediate",
            "description": "Applies a bash fix script generated by oscap. Can optionally specify rule IDs to filter fixes to apply.",
            "parameters": {
                "type": "object",
                "properties": {
                    "rule_ids": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of rule IDs to fix. Leave empty to fix all failed rules."
                    }
                }
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "generate_report",
            "description": "Generates the user-facing HTML report based on the latest scan.",
            "parameters": {"type": "object", "properties": {}}
        }
    }
]

ANTHROPIC_TOOLS = [
    {
        "name": t["function"]["name"],
        "description": t["function"]["description"],
        "input_schema": t["function"]["parameters"]
    }
    for t in TOOLS_SCHEMA
]

def dispatch_tool(name, args):
    if name == "detect_os":
        return detect_os()
    elif name == "check_prerequisites":
        return check_prerequisites()
    elif name == "run_scan":
        return run_scan()
    elif name == "parse_results":
        return parse_results()
    elif name == "remediate":
        rule_ids = args.get("rule_ids", [])
        return remediate(rule_ids)
    elif name == "generate_report":
        return generate_report()
    else:
        return f"Tool {name} not found."

class AgentSession:
    def __init__(self, provider, api_key):
        self.provider = provider
        self.api_key = api_key
        self.messages = []
        
        if provider == "anthropic":
            from anthropic import Anthropic
            self.client = Anthropic(api_key=api_key)
        elif provider == "openai":
            from openai import OpenAI
            self.client = OpenAI(api_key=api_key)

    def run_conversation(self, user_text):
        if self.provider == "anthropic":
            return self._run_anthropic(user_text)
        elif self.provider == "openai":
            return self._run_openai(user_text)

    def _run_anthropic(self, user_text):
        self.messages.append({"role": "user", "content": user_text})

        while True:
            response = self.client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=2048,
                system=SYSTEM_PROMPT,
                messages=self.messages,
                tools=ANTHROPIC_TOOLS
            )

            # process the Assistant's message blocks
            self.messages.append({"role": "assistant", "content": response.content})

            # Check if there are tool calls
            tool_calls = [blk for blk in response.content if blk.type == "tool_use"]
            if not tool_calls:
                # No tools -> return text
                texts = [blk.text for blk in response.content if blk.type == "text"]
                return " ".join(texts)

            # We have tool calls, process them
            tool_results = []
            for tc in tool_calls:
                # execute
                print(f"Agent is running tool: {tc.name}...")
                result_str = dispatch_tool(tc.name, tc.input)
                # print(f"Tool {tc.name} returned {len(result_str)} characters.")
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": tc.id,
                    "content": result_str
                })

            self.messages.append({"role": "user", "content": tool_results})


    def _run_openai(self, user_text):
        # ensure System Prompt is at the front
        if not self.messages or self.messages[0]["role"] != "system":
            self.messages.insert(0, {"role": "system", "content": SYSTEM_PROMPT})
            
        self.messages.append({"role": "user", "content": user_text})
        
        while True:
            response = self.client.chat.completions.create(
                model="gpt-4o",
                messages=self.messages,
                tools=TOOLS_SCHEMA,
                tool_choice="auto"
            )
            message = response.choices[0].message
            self.messages.append(message)
            
            if not message.tool_calls:
                return message.content
                
            for tc in message.tool_calls:
                args = json.loads(tc.function.arguments)
                print(f"Agent is running tool: {tc.function.name}...")
                result_str = dispatch_tool(tc.function.name, args)
                # print(f"Tool {tc.function.name} returned {len(result_str)} characters.")
                self.messages.append({
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "name": tc.function.name,
                    "content": result_str
                })
