import os
import json
import time
from .tools.detect import detect_os
from .tools.prereqs import check_prerequisites
from .tools.scan import run_scan
from .tools.parse import parse_results
from .tools.remediate import remediate
from .tools.report import generate_report

SYSTEM_PROMPT = """You are stigman, an AI assistant that runs DISA STIG compliance scans on Ubuntu systems using OpenSCAP. You help users scan their system, understand results, and remediate findings.
When asked to run a scan, use the `execute_full_scan` tool. NEVER try to guess or hallucinate scan results. Always report the summary pass/fail counts and highlight critical failures.
When asked to remediate, confirm what will be changed before applying fixes. IMPORTANT: Because remediation scripts can be large, you must only propose and apply fixes in chunks of MAXIMUM 5 rules at a time. After fixing 5 rules, ask the user if they'd like to continue.
Be concise and terminal-friendly in your responses — no markdown headers or bullet points, use simple text formatting."""

TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "execute_full_scan",
            "description": "Orchestrates the entire scan pipeline: detects OS, checks prerequisites, runs the DISA STIG scan via OpenSCAP, parses the results, generates the HTML report, and returns a JSON summary of passes and failures.",
            "parameters": {"type": "object", "properties": {}}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "remediate",
            "description": "Applies a bash fix script generated by oscap. Can optionally specify rule IDs to filter fixes to apply.",
            "parameters": {
                "type": "object",
                "properties": {
                    "rule_ids": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of rule IDs to fix. Leave empty to fix all failed rules."
                    }
                }
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "generate_report",
            "description": "Generates the user-facing HTML report based on the latest scan.",
            "parameters": {"type": "object", "properties": {}}
        }
    }
]

ANTHROPIC_TOOLS = [
    {
        "name": t["function"]["name"],
        "description": t["function"]["description"],
        "input_schema": t["function"]["parameters"]
    }
    for t in TOOLS_SCHEMA
]


# Fallback order for OpenRouter free-tier 429s (best reasoning → lightest)
OPENROUTER_FALLBACK_MODELS = [
    "meta-llama/llama-3.3-70b-instruct:free",
    "nousresearch/hermes-3-llama-3.1-405b:free",
    "google/gemma-4-31b-it:free",
    "google/gemma-4-26b-a4b-it:free",
    "google/gemma-3-27b-it:free",
    "google/gemma-3-12b-it:free",
    "google/gemma-3-4b-it:free",
    "meta-llama/llama-3.2-3b-instruct:free",
    "google/gemma-3n-e4b-it:free",
    "google/gemma-3n-e2b-it:free",
]

def perform_full_scan():
    print("Agent is orchestrating full scan pipeline...")
    os_res = detect_os()
    if "Error" in os_res:
        return os_res
        
    pre_res = check_prerequisites()
    if "Error" in pre_res:
        return pre_res
        
    scan_res = run_scan()
    if "Error" in scan_res:
        return scan_res
        
    # Generate report in background too
    generate_report()
    
    return parse_results()

def dispatch_tool(name, args):

    if name == "execute_full_scan":
        return perform_full_scan()
    elif name == "remediate":
        rule_ids = args.get("rule_ids", [])
        return remediate(rule_ids)
    else:
        return f"Tool {name} not found."

class AgentSession:
    def __init__(self, provider, api_key, model=None):
        self.provider = provider
        self.api_key = api_key
        self.messages = []
        
        if provider == "anthropic":
            from anthropic import Anthropic
            self.client = Anthropic(api_key=api_key)
            self.model = "claude-sonnet-4-20250514"
        elif provider == "openai":
            from openai import OpenAI
            self.client = OpenAI(api_key=api_key)
            self.model = "gpt-4o"
        elif provider == "openrouter":
            from openai import OpenAI
            self.client = OpenAI(
                api_key=api_key,
                base_url="https://openrouter.ai/api/v1",
                default_headers={
                    "HTTP-Referer": "https://github.com/TheSTIGMan/stigman",
                    "X-Title": "stigman",
                }
            )
            self.model = model or "meta-llama/llama-3.3-70b-instruct:free"

    def run_conversation(self, user_text):
        if self.provider == "anthropic":
            return self._run_anthropic(user_text)
        elif self.provider in ("openai", "openrouter"):
            return self._run_openai(user_text)

    def _run_anthropic(self, user_text):
        self.messages.append({"role": "user", "content": user_text})

        while True:
            response = self.client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=2048,
                system=SYSTEM_PROMPT,
                messages=self.messages,
                tools=ANTHROPIC_TOOLS
            )

            # process the Assistant's message blocks
            self.messages.append({"role": "assistant", "content": response.content})

            # Check if there are tool calls
            tool_calls = [blk for blk in response.content if blk.type == "tool_use"]
            if not tool_calls:
                # No tools -> return text
                texts = [blk.text for blk in response.content if blk.type == "text"]
                return " ".join(texts)

            # We have tool calls, process them
            tool_results = []
            for tc in tool_calls:
                # execute
                print(f"Agent is running tool: {tc.name}...")
                result_str = dispatch_tool(tc.name, tc.input)
                # print(f"Tool {tc.name} returned {len(result_str)} characters.")
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": tc.id,
                    "content": result_str
                })

            self.messages.append({"role": "user", "content": tool_results})


    def _run_openai(self, user_text):
        # ensure System Prompt is at the front
        if not self.messages or self.messages[0]["role"] != "system":
            self.messages.insert(0, {"role": "system", "content": SYSTEM_PROMPT})

        self.messages.append({"role": "user", "content": user_text})

        # Build fallback model queue for openrouter
        if self.provider == "openrouter":
            remaining = [self.model] + [
                m for m in OPENROUTER_FALLBACK_MODELS if m != self.model
            ]
        else:
            remaining = [self.model]

        current_model = remaining[0]
        max_retries = 3

        while True:
            retries = 0
            response = None
            
            while retries <= max_retries:
                try:
                    response = self.client.chat.completions.create(
                        model=current_model,
                        messages=self.messages,
                        tools=TOOLS_SCHEMA,
                        tool_choice="auto"
                    )
                    break # Success
                except Exception as e:
                    err = str(e)
                    
                    if "404" in err and self.provider == "openrouter" and len(remaining) > 1:
                        # Tools not supported. Don't bother retrying, jump to fallback immediately
                        break
                        
                    if "429" in err:
                        if retries < max_retries:
                            wait_time = 2 ** (retries + 1) # 2s, 4s, 8s
                            print(f"Rate limited (429) on {current_model}. Retrying in {wait_time}s...")
                            time.sleep(wait_time)
                            retries += 1
                            continue
                        elif self.provider == "openrouter" and len(remaining) > 1:
                            # Exhausted retries, fallback below
                            break
                            
                    # Raise for any other unhandled errors or if we exhausted list
                    raise e
            
            # If response is still None after the inner loop, it means we hit a break due to 404 or exhausted retries, 
            # and we need to drop to a fallback model if we are openrouter
            if response is None and self.provider == "openrouter" and len(remaining) > 1:
                remaining.pop(0)
                current_model = remaining[0]
                print(f"Model capacity/features exhausted — switching to fallback model: {current_model}")
                continue
            elif response is None:
                raise Exception(f"All models rate-limited or failed for {current_model}")

            message = response.choices[0].message
            self.messages.append(message)

            if not message.tool_calls:
                return message.content

            for tc in message.tool_calls:
                args = json.loads(tc.function.arguments)
                print(f"Agent is running tool: {tc.function.name}...")
                result_str = dispatch_tool(tc.function.name, args)
                self.messages.append({
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "name": tc.function.name,
                    "content": result_str
                })
